<?php
echo "<!doctype html>\n";
echo "<html lang=\"en\">\n";
echo "  <head>\n";
echo "    <!-- Required meta tags -->\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
echo "\n";
echo "    <!-- Bootstrap CSS -->\n";
echo "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCk></script>\n";
echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\n";
echo "    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n";
echo "    <title>Login</title>\n";
echo "  </head>\n";
echo "  <body>\n";
echo "    <style>\n";
echo "\n";
echo "\n";
echo "      body {\n";
echo "        width: 100%;\n";
echo "        height: 100%;\n";
echo "        background-color: #222;\n";
echo "        border-color: #080808;\n";
echo "      }\n";
echo "      .home{\n";
echo "        width: 100%;\n";
echo "        height: 100%;\n";
echo "        display: flex;\n";
echo "        align-items: center;\n";
echo "        justify-content: center;\n";
echo "      }\n";
echo "      .item{\n";
echo "        width: 500px;\n";
echo "        height: 500px;\n";
echo "        background: #fff;\n";
echo "\n";
echo "      }\n";
echo "\n";
echo "      .in{\n";
echo "        padding: 15px;\n";
echo "\n";
echo "      }\n";
echo "      .text-center{\n";
echo "      padding: 15px;\n";
echo "\n";
echo "      }\n";
echo "      .logo{\n";
echo "        width: 90px;\n";
echo "        height: 90px;\n";
echo "        border-radius: 100%;\n";
echo "        margin: 0 auto;\n";
echo "        border: 3px solid #94979c;\n";
echo "        color: #94979c;\n";
echo "        margin-bottom: 20px;\n";
echo "        padding: 2px;\n";
echo "        line-height: 90px;\n";
echo "        color: #eee;\n";
echo "      }\n";
echo "      .logo h1{\n";
echo "        font-weight: 300;\n";
echo "        font-size: 40px;\n";
echo "        padding: 20px;\n";
echo "        align-items: center;\n";
echo "        justify-content: center;\n";
echo "        display: flex;\n";
echo "        color: #eee;\n";
echo "      }\n";
echo "      input[type=text],\n";
echo "      input[type=password]{\n";
echo "        background: 0 0;\n";
echo "        border: 0;\n";
echo "        box-shadow: none;\n";
echo "        border-bottom: 1px solid #afb5c1;\n";
echo "        border-radius: 0;\n";
echo "\n";
echo "\n";
echo "\n";
echo "      }\n";
echo "      .lg{\n";
echo "        margin-bottom: 20px;\n";
echo "      }\n";
echo "      .input.group.addon{\n";
echo "        background: 0 0;\n";
echo "        border: 0;\n";
echo "        color: #afb5c1;\n";
echo "        padding: 0 0 5px 0;\n";
echo "\n";
echo "      }\n";
echo "      .btn-dark{\n";
echo "        border: 0;\n";
echo "        border-radius: 30px;\n";
echo "      }\n";
echo "      input[type=text],\n";
echo "      input[type=password]:focus{\n";
echo "        box-shadow:none;\n";
echo "\n";
echo "      }\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "      /* Tabs*/\n";
echo "      section {\n";
echo "        background: #222;\n";
echo "        border-color: #080808;\n";
echo "        color: white;\n";
echo "        border-radius: 1em;\n";
echo "        padding: 1em;\n";
echo "        position: absolute;\n";
echo "        top: 50%;\n";
echo "        left: 50%;\n";
echo "        margin-right: -50%;\n";
echo "        transform: translate(-50%, -50%) }\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "      }\n";
echo "\n";
echo "\n";
echo "      #tabs{\n";
echo "        background-color: #222;\n";
echo "        border-color: #080808;\n";
echo "          color: #eee;\n";
echo "      }\n";
echo "\n";
echo "\n";
echo "      #tabs .nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {\n";
echo "          color: #f3f3f3;\n";
echo "          background-color: transparent;\n";
echo "          border-color: transparent transparent #f3f3f3;\n";
echo "          border-bottom: 4px solid !important;\n";
echo "          font-size: 20px;\n";
echo "          font-weight: bold;\n";
echo "\n";
echo "          display: flex;\n";
echo "          align-items: center;\n";
echo "          justify-content: center;\n";
echo "      }\n";
echo "      #tabs .nav-tabs .nav-link {\n";
echo "          border: 1px solid transparent;\n";
echo "          border-top-left-radius: .25rem;\n";
echo "          border-top-right-radius: .25rem;\n";
echo "          color: #eee;\n";
echo "          font-size: 20px;\n";
echo "\n";
echo "      }\n";
echo "\n";
echo "    </style>\n";
echo "\n";
echo "      <nav class=\"navbar navbar-expand-lg navbar-light bg-dark navbar-dark\">\n";
echo "  <a class=\"navbar-brand\"href=\"#\">HELL <i class=\"fa fa-rebel\" aria-hidden=\"true\"></i></a>\n";
echo "  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
echo "    <span class=\"navbar-toggler-icon\"></span>\n";
echo "  </button>\n";
echo "\n";
echo "  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n";
echo "    <ul class=\"navbar-nav mr-auto\">\n";
echo "      <li class=\"nav-item active\">\n";
echo "        <a class=\"nav-link\" href=\"#\">Home <span class=\"sr-only\">(current)</span></a>\n";
echo "      </li>\n";
echo "      <li class=\"nav-item active\">\n";
echo "        <a class=\"nav-link\" href=\"#\">Login/Signup <span class=\"sr-only\">(current)</span></a>\n";
echo "      </li>\n";
echo "      <li class=\"nav-item dropdown\">\n";
echo "        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n";
echo "          Dropdown\n";
echo "        </a>\n";
echo "        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n";
echo "          <a class=\"dropdown-item\" href=\"#\">Action</a>\n";
echo "          <a class=\"dropdown-item\" href=\"#\">Another action</a>\n";
echo "          <div class=\"dropdown-divider\"></div>\n";
echo "          <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n";
echo "        </div>\n";
echo "      </li>\n";
echo "\n";
echo "    </ul>\n";
echo "    <form class=\"form-inline my-2 my-lg-0\">\n";
echo "      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n";
echo "      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n";
echo "    </form>\n";
echo "    <li class=\"nav-item active\">\n";
echo "      <a class=\"nav-link\" href=\"#\">Logout <span class=\"sr-only\">(current)</span></a>\n";
echo "    </li>\n";
echo "  </div>\n";
echo "</nav>\n";
echo "<!--  end navbar -->\n";
echo "\n";
echo "<section id=\"tabs\">\n";
echo "	<div class=\"container\">\n";
echo "\n";
echo "		<div class=\"row\">\n";
echo "			<div class=\"col-xs-12 \">\n";
echo "				<nav>\n";
echo "					<div class=\"nav nav-tabs nav-fill\" id=\"nav-tab\" role=\"tablist\">\n";
echo "						<a class=\"nav-item nav-link active\" id=\"nav-home-tab\" data-toggle=\"tab\" href=\"#nav-home\" role=\"tab\" aria-controls=\"nav-login\" aria-selected=\"true\">Login</a>\n";
echo "						<a class=\"nav-item nav-link\" id=\"nav-profile-tab\" data-toggle=\"tab\" href=\"#nav-profile\" role=\"tab\" aria-controls=\"nav-signup\" aria-selected=\"false\">Signup</a>\n";
echo "\n";
echo "					</div>\n";
echo "				</nav>\n";
echo "				<div class=\"tab-content py-3 px-3 px-sm-0\" id=\"nav-tabContent\">\n";
echo "					<div class=\"tab-pane fade show active\" id=\"nav-home\" role=\"tabpanel\" aria-labelledby=\"nav-home-tab\">\n";
echo "            <!--login--->\n";
echo "            <form action=\"#\" class=\"form-horizontal\">\n";
echo "            <div class=\"logo\">\n";
echo "              <h1><i class=\"fa fa-reddit-alien\" aria-hidden=\"true\"></i></h1>\n";
echo "            </div>\n";
echo "            <div class=\"input-group lg\">\n";
echo "              <span class=\"input-group-addon\"><i class=\"fa fa-snapchat-ghost\" aria-hidden=\"true\"></i></span>\n";
echo "              <input type=\"text\" class=\"form-control\" placeholder=\"Enter email\">\n";
echo "            </div>\n";
echo "            <div class=\"input-group lg\">\n";
echo "              <span class=\"input-group-addon\"><i class=\"fa fa-lock\" aria-hidden=\"true\"></i></span>\n";
echo "              <input type=\"password\" class=\"form-control\" placeholder=\"Enter password\">\n";
echo "            </div>\n";
echo "            <div class=\"form-group in\">\n";
echo "              <input type=\"submit\" class=\"btn btn-dark btn-block\" value = \"Login\">\n";
echo "            </div>\n";
echo "\n";
echo "\n";
echo "            <!-- end login -->\n";
echo "					</div>\n";
echo "					<div class=\"tab-pane fade\" id=\"nav-profile\" role=\"tabpanel\" aria-labelledby=\"nav-profile-tab\">\n";
echo "            <div class=\"container\">\n";
echo "                <form class=\"form-horizontal\" role=\"form\" method=\"POST\" action=\"/register\">\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"col-md-3\"></div>\n";
echo "                        <div class=\"col-md-6\">\n";
echo "                            <h2>Register</h2>\n";
echo "                            <hr>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"col-md-3 field-label-responsive\">\n";
echo "                            <label for=\"name\">Name</label>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-6\">\n";
echo "                            <div class=\"form-group\">\n";
echo "                                <div class=\"input-group mb-2 mr-sm-2 mb-sm-0\">\n";
echo "                                    <div class=\"input-group-addon lg\" style=\"width: 2.6rem\"><i class=\"fa fa-user\"></i></div>\n";
echo "                                    <input type=\"text\" name=\"name\" class=\"form-control\" id=\"name\"\n";
echo "                                           placeholder=\"John Doe\" required autofocus>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-3\">\n";
echo "                            <div class=\"form-control-feedback\">\n";
echo "                                    <span class=\"text-danger align-middle\">\n";
echo "                                        <!-- Put name validation error messages here -->\n";
echo "                                    </span>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"col-md-3 field-label-responsive\">\n";
echo "                            <label for=\"email\">E-Mail</label>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-6\">\n";
echo "                            <div class=\"form-group\">\n";
echo "                                <div class=\"input-group mb-2 mr-sm-2 mb-sm-0\">\n";
echo "                                    <div class=\"input-group-addon lg\" style=\"width: 2.6rem\"><i class=\"fa fa-at\"></i></div>\n";
echo "                                    <input type=\"text\" name=\"email\" class=\"form-control\" id=\"email\"\n";
echo "                                           placeholder=\"you@example.com\" required autofocus>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-3\">\n";
echo "                            <div class=\"form-control-feedback\">\n";
echo "                                    <span class=\"text-danger align-middle\">\n";
echo "                                        <!-- Put e-mail validation error messages here -->\n";
echo "                                    </span>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"col-md-3 field-label-responsive\">\n";
echo "                            <label for=\"password\">Password</label>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-6\">\n";
echo "                            <div class=\"form-group has-danger\">\n";
echo "                                <div class=\"input-group mb-2 mr-sm-2 mb-sm-0\">\n";
echo "                                    <div class=\"input-group-addon lg\" style=\"width: 2.6rem\"><i class=\"fa fa-key\"></i></div>\n";
echo "                                    <input type=\"password\" name=\"password\" class=\"form-control\" id=\"password\"\n";
echo "                                           placeholder=\"Enter password\" required>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-3\">\n";
echo "                            <div class=\"form-control-feedback\">\n";
echo "                              <span class=\"text-danger align-middle\">\n";
echo "                                  <!-- Put password validation error messages here -->\n";
echo "                              </span>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"col-md-3 field-label-responsive\">\n";
echo "                            <label for=\"password\">Confirm Password</label>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-6\">\n";
echo "                            <div class=\"form-group\">\n";
echo "                                <div class=\"input-group mb-2 mr-sm-2 mb-sm-0\">\n";
echo "                                    <div class=\"input-group-addon lg\" style=\"width: 2.6rem\">\n";
echo "                                        <i class=\"fa fa-repeat\"></i>\n";
echo "                                    </div>\n";
echo "                                    <input type=\"password\" name=\"password-confirmation\" class=\"form-control\"\n";
echo "                                           id=\"password-confirm\" placeholder=\"Re-enter password\" required>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "\n";
echo "                        <div class=\"text-center\">\n";
echo "                            <button type=\"submit\" class=\"btn btn-dark btn-block\"><i class=\"fa fa-user-plus\"></i> SignUp</button>\n";
echo "                        </div>\n";
echo "\n";
echo "\n";
echo "                </form>\n";
echo "            </div>\n";
echo "					</div>\n";
echo "\n";
echo "				</div>\n";
echo "\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "</section>\n";
echo "<!-- ./Tabs -->\n";
echo "<!-- Bootstrap core JavaScript\n";
echo "    ================================================== -->\n";
echo "	<!-- Placed at the end of the document so the pages load faster -->\n";
echo "	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\n";
echo "	<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\n";
echo "                                                                                                                                                                        ?>?>                                                                                                                                                               ?>\n";
echo "  </body>\n";
echo "</html>\n";
?>